import os
from typing import Any

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError as exc:
    raise ImportError(
        "psycopg is required for the Supabase database connection."
    ) from exc


class Row(dict):
    """Small sqlite3.Row-compatible mapping for the bot's existing code."""

    def __getitem__(self, key: Any) -> Any:
        if isinstance(key, int):
            try:
                return list(self.values())[key]
            except IndexError as exc:
                raise IndexError(key) from exc
        return super().__getitem__(key)


class Cursor:
    def __init__(self, cursor):
        self._cursor = cursor
        self._pending_row = None
        self.lastrowid = None

    def execute(self, sql: str, parameters=()):
        normalized = " ".join(sql.strip().split())

        if normalized.upper().startswith("PRAGMA "):
            self._pending_row = None
            self.lastrowid = None
            return self

        sql = sql.replace("?", "%s")
        sql = sql.replace(
            "INTEGER PRIMARY KEY AUTOINCREMENT",
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        )
        sql = sql.replace(
            "TEXT DEFAULT CURRENT_TIMESTAMP",
            "TEXT DEFAULT (CURRENT_TIMESTAMP::text)",
        )

        statement = sql.lstrip()
        if statement.upper().startswith("INSERT") and "RETURNING" not in statement.upper():
            sql = sql.rstrip().rstrip(";") + " RETURNING id;"

        self._cursor.execute(sql, parameters or ())
        self._pending_row = None
        self.lastrowid = None

        if statement.upper().startswith("INSERT"):
            row = self._cursor.fetchone()
            if row:
                row = Row(row)
                self._pending_row = row
                self.lastrowid = row.get("id")

        return self

    def fetchone(self):
        if self._pending_row is not None:
            row = self._pending_row
            self._pending_row = None
            return row

        row = self._cursor.fetchone()
        return Row(row) if row is not None else None

    def fetchall(self):
        rows = self._cursor.fetchall()
        return [Row(row) for row in rows]

    @property
    def rowcount(self):
        return self._cursor.rowcount

    def close(self):
        return self._cursor.close()


class Connection:
    def __init__(self, database_url: str):
        self._connection = psycopg.connect(
            database_url,
            row_factory=dict_row,
            autocommit=False,
        )
        self.row_factory = Row

    def execute(self, sql: str, parameters=()):
        cursor = Cursor(self._connection.cursor())
        return cursor.execute(sql, parameters)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def connect(database=None, *args, **kwargs):
    database_url = (
        os.getenv("SUPABASE_DB_URL", "").strip()
        or os.getenv("DATABASE_URL", "").strip()
    )

    if not database_url:
        raise RuntimeError(
            "SUPABASE_DB_URL yoki DATABASE_URL environment variable topilmadi."
        )

    return Connection(database_url)


Error = Exception
DatabaseError = Exception
OperationalError = Exception
IntegrityError = Exception
